# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CS4405 Analysis of Concurrent and Distributed Programs
tagline: Analysis of Concurrent and Distributed Programs
description: 
repository: cs4405/course-webpage

author: Soham Chakraborty, Burcu Kulahcioglu Ozkan
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://cs4405.github.io' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
google_site_verification: ''

# Theme settings
remote_theme: pmarsceill/just-the-docs
color_scheme: cs4405
search_enabled: false
heading_anchors: false
permalink: pretty
footer_content: 'Soham Chakraborty, Burcu Kulahcioglu Ozkan, TU Delft &copy; 2022 <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>'

# Collections for website data
collections:
  staffers:
  modules:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag
